/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package othello;

import othello.base.Board;
import othello.view.CommandlineView;

public class App {

  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    Board board = new Board();
    CommandlineView.update(board);
  }

}
