/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package othello;

import othello.view.ConsoleView;
import othello.view.OthelloView;

public class App {

  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    OthelloView view = new ConsoleView();
    Match match = new Match(view);
    new Thread(match).start();
  }

}
